swagger: "2.0"
info:
  description: "Elevate APIs (use api key `special-key` to test authorization filters)"
  version: "1.0.0 (beta)"
  title: "Elevate API"
  # termsOfService: "http://swagger.io/terms/"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: ".swagger.io"
host: "gdl-service-layer-uak3zqgy4q-uc.a.run.app"
basePath: "/v2"
schemes:
  - "https"
  - "http"

#------ API ------
paths:
  #VERIFY VendorAccount's ID... (if verified) CREATE new ConnectedAccount
  /api/connected-account/verify-vendor:
    post:
      tags:
        - "verify vendorAccountId + create new ConnectedAccount (if verified)"
      summary: "verifies vendor account's ID... (if verified) create new ConnectedAccount"
      operationId: "verifyVendorAccount({ teamAccountId, vendorName, vendorAccountId })"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        # - "application/xml"
        - "application/json"
      parameters:
        - name: "teamAccountId"
          in: "formData"
          description: '(eg; "Ldsn3m2vds4hvgd28")'
          required: true
          type: "string"
        - name: "vendorName"
          in: "formData"
          description: '(eg; "OD")'
          required: true
          type: "string"
        - name: "vendorAccountId"
          in: "formData"
          description: "(eg; 87634123)"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "{ \ndata: { \nconnectedAccountId, \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus, \ncreatedAt, \nupdatedAt \n}, \nsuccess: true, \nerror: null \n}"
        "500":
          description: "{ \ndata: { \nconnectedAccountId: null, \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus: \"ERROR\" \n}, \nsucces: false, \nerror: error \n}"
      # security:
      #   - petstore_auth:
      #       - "write:connected-accounts"
      #       - "read:connected-accounts"

  #GET ConnectedAccountActivity by ID
  /api/connected-account/current-account-activity/{teamAccountId}:
    get:
      tags:
        - "fetch ConnectedAccountActivity by teamAccountID"
      summary: 'given a "teamAccountId" string, API fetches ConnectedAccountActivity entries from BigQuery (dataset: "connected_account" | table: "connected_account_activity")'
      operationId: "getConnectedAccountActivity"
      produces:
        # - "application/xml"
        - "application/json"
      parameters:
        - name: "teamAccountId"
          in: "path"
          description: '(eg; "Ldsn3m2vds4hvgd28")'
          required: true
          type: "string"
          # format: "int64"
      responses:
        "200":
          description: "{ \ndata: [ \n{ \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus, \nproductDesc, \nproductCode, \nnetSales, \nlistPrice, \nprogramPrice, \nqtySold, \norderCompleteDate \n}, \n...{} \n], \nsuccess: true, \nerror: null \n}"
        "500":
          description: "{ \ndata: null, \nsucces: false, \nerror: error \n}"
      # security:
      #   - api_key: []

  #DELETE ConnectedAccount by ID
  /api/connected-account/remove-connected-account/{connectedAccountId}:
    delete:
      tags:
        - "delete ConnectedAccount by connectedAccountId"
      summary: 'given a "connectedAccountId" string, API removes a single ConnectedAccount entry from Cloud SQL (database: "production" | table: "connected_account")'
      operationId: "deleteConnectedAccount"
      produces:
        # - "application/xml"
        - "application/json"
      parameters:
        - name: "connectedAccountId"
          in: "path"
          description: '(eg; "04a826e2-909f-47c7-980e-97c2ceaae1a0")'
          required: true
          type: "string"
          format: "uuid"
      responses:
        "200":
          description: "{ \ndata: { \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus, \ncreatedAt, \nupdatedAt \n}, \nsuccess: true, \nerror: null \n}"
        "500":
          description: "{ \ndata: null, \nsucces: false, \nerror: error \n}"
      # security:
      #   - api_key: []

#------ SECURITY ------
securityDefinitions:
  # petstore_auth:
  #   type: "oauth2"
  # authorizationUrl: "http://.swagger.io/oauth/dialog"
  # flow: "implicit"
  # scopes:
  #   write:connected-accounts: "modify connected-accounts in your account"
  #   read:connected-accounts: "read your connected-accounts"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

#------ SCHEMA ------
definitions:
  ConnectedAccount:
    type: "object"
    properties:
      connectedAccountId:
        type: "string"
        format: "uuid"
      vendorName:
        type: "string"
      vendorAccountId:
        type: "number"
        format: "int64"
      teamAccountId:
        type: "string"
      status:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
    xml:
      name: "ConnectedAccount"
  ConnectedAccountActivity:
    type: "object"
    properties:
      vendorName:
        type: "string"
      vendorAccountId:
        type: "number"
        format: "int64"
      teamAccountId:
        type: "string"
      status:
        type: "string"
      productDesc:
        type: "string"
      productCode:
        type: "string"
      netSales:
        type: "number"
        format: "float64"
      listPrice:
        type: "number"
        format: "float64"
      programPrice:
        type: "number"
        format: "float64"
      qtySold:
        type: "number"
        format: "int64"
      orderCompleteDate:
        type: "string"
        format: "date-time"
    xml:
      name: "ConnectedAccountActivity"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"

#------ EXTERNAL RESOURCES ------
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
