swagger: "2.0"
info:
  description: "Elevate APIs (use api key `special-key` to test authorization filters)"
  version: "1.0.0 (beta)"
  title: "Elevate API"
  # termsOfService: "http://swagger.io/terms/"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: ".swagger.io"
host: "gdl-service-layer-uak3zqgy4q-uc.a.run.app"
basePath: "/v2"
schemes:
  - "https"
  - "http"

#------ API ------
paths:
  #VERIFY VendorAccount's ID... (if verified) CREATE new ConnectedAccount
  /api/connected-account/verify-vendor:
    post:
      tags:
        - "verify vendorAccountId + create new ConnectedAccount (if verified)"
      summary: "verifies vendor account's ID... (if verified) create new ConnectedAccount"
      operationId: "verifyVendorAccount({ teamAccountId, vendorName, vendorAccountId })"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        # - "application/xml"
        - "application/json"
      parameters:
        - name: "teamAccountId"
          in: "formData"
          description: '(eg; "Ldsn3m2vds4hvgd28")'
          required: true
          type: "string"
        - name: "vendorName"
          in: "formData"
          description: '(eg; "OD" or "EA Express" or "Dell")'
          required: true
          type: "string"
        - name: "vendorAccountId"
          in: "formData"
          description: "(eg; 87634123)"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "{ \ndata: { \nconnectedAccountId, \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus, \ncreatedAt, \nupdatedAt \n}, \nsuccess: true, \nerror: null \n}"
        "500":
          description: "{ \ndata: { \nconnectedAccountId: null, \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus: \"ERROR\" \n}, \nsucces: false, \nerror: error \n}"
      # security:
      #   - petstore_auth:
      #       - "write:connected-accounts"
      #       - "read:connected-accounts"

  #GET ConnectedAccountActivity by ID
  /api/connected-account/current-account-activity/{teamAccountId}:
    get:
      tags:
        - "fetch ConnectedAccountActivity by teamAccountID"
      summary: 'given a "teamAccountId" string, API fetches all entries from Snowflake (database: "elevate_accounts" | table: "elevate_accounts_activity")'
      operationId: "getConnectedAccountActivity"
      produces:
        # - "application/xml"
        - "application/json"
      parameters:
        - name: "teamAccountId"
          in: "path"
          description: '(eg; "Ldsn3m2vds4hvgd28")'
          required: true
          type: "string"
          # format: "int64"
      responses:
        "200":
          description: "{ \ndata: [ \n{ \nconnectedAccountId, \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus, \ncreatedAt, \nupdatedAt, \ndecisionMakerId, \ndecisionMakerName, \ngrandparentId, \ngrandparentName, \nparentId, \nparentName, \naccountId, \ncustomerName, \nshipToId, \naddressKey, \nshipToName, \naddress1, \naddress2, \ncity, \nstate, \nzipCode, \ncustomerCreateDate, \nfirstOrderDate, \ncustomerDepartment, \ncustomerPurchaseOrder, \ncustomerDesktop, \ncustomerReleaseField, \ncontractIndicator, \ncontactName, \nphone, \nwebUserId, \nwebUserEmail, \nodProductCode, \nproductDescription, \nuom, \nwholesalerProductCode, \npackQty, \nqtySold, \ncorePlanId, \netSales, \ncontractNetSales, \nprogramPrice, \nretailListPrice, \nparentOrderId, \norderSuborderId, \norderSourceName, \norderSourceCode, \nproductCategoryname, \nitemDepartmentId, \nitemDepartmentName, \nitemClassId, \nitemClassName, \nitemSubclassId, \nitemSubclassName, \nrecycledFlag, \nprimarySupplierId, \nprimarySuppliername, \norderSupplierMinorityBusinessCode, \norderSupplierMinorityBusinessDesc, \norderSupplierMinorityCategoryCode, \norderSupplierMinorityCategoryDesc, \norderCreateDate, \norderCompleteDate, \ninventoryLocation, \nspecialProductId, \nproductId, \nspecialType, \nspecialMod, \nspecialLimit, \ntotalIssued, \ntotalClaimed, \ntotalAvailable, \ndateActivated, \ndateDeactivated, \nspecialRestrictions \n}, \n...{} \n], \nsuccess: true, \nerror: null \n}"
        "500":
          description: "{ \ndata: null, \nsucces: false, \nerror: error \n}"
      # security:
      #   - api_key: []

  #DELETE ConnectedAccount by ID
  /api/connected-account/remove/{connectedAccountId}:
    delete:
      tags:
        - "delete ConnectedAccount by connectedAccountId"
      summary: 'given a "connectedAccountId" string, API removes a single ConnectedAccount entry from Cloud SQL (database: "production" | table: "connected_account")'
      operationId: "deleteConnectedAccount"
      produces:
        # - "application/xml"
        - "application/json"
      parameters:
        - name: "connectedAccountId"
          in: "path"
          description: '(eg; "04a826e2-909f-47c7-980e-97c2ceaae1a0")'
          required: true
          type: "string"
          format: "uuid"
      responses:
        "200":
          description: "{ \ndata: { \nvendorName, \nvendorAccountId, \nteamAccountId, \nstatus, \ncreatedAt, \nupdatedAt \n}, \nsuccess: true, \nerror: null \n}"
        "500":
          description: "{ \ndata: null, \nsucces: false, \nerror: error \n}"
      # security:
      #   - api_key: []

#------ SECURITY ------
securityDefinitions:
  # petstore_auth:
  #   type: "oauth2"
  # authorizationUrl: "http://.swagger.io/oauth/dialog"
  # flow: "implicit"
  # scopes:
  #   write:connected-accounts: "modify connected-accounts in your account"
  #   read:connected-accounts: "read your connected-accounts"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

#------ SCHEMA ------
definitions:
  ConnectedAccount:
    type: "object"
    properties:
      connectedAccountId:
        type: "string"
        format: "uuid"
      vendorName:
        type: "string"
      vendorAccountId:
        type: "number"
        format: "int64"
      teamAccountId:
        type: "string"
      status:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
    xml:
      name: "ConnectedAccount"
  ConnectedAccountActivity:
    type: "object"
    properties:
      vendorName:
        type: "string"
      vendorAccountId:
        type: "number"
        format: "int64"
      teamAccountId:
        type: "string"
      status:
        type: "string"
      createdAt:
        type: "string"
        format: "date"
      updatedAt:
        type: "string"
        format: "date"
      decisionMakerId:
        type: "string"
      decisionMakerName:
        type: "string"
      grandparentId:
        type: "number"
        format: "int64"
      grandparentName:
        type: "string"
      parentId:
        type: "number"
        format: "int64"
      parentName:
        type: "string"
      accountId:
        type: "number"
        format: "int64"
      customerName:
        type: "string"
      shipToId:
        type: "number"
        format: "int64"
      addressKey:
        type: "string"
      shipToName:
        type: "string"
      address1:
        type: "string"
      address2:
        type: "string"
      city:
        type: "string"
      state:
        type: "string"
      zipCode:
        type: "string"
      customerCreateDate:
        type: "string"
        format: "date"
      firstOrderDate:
        type: "string"
        format: "date"
      customerDepartment:
        type: "string"
      customerPurchaseOrder:
        type: "string"
      customerDesktop:
        type: "string"
      customerReleaseField:
        type: "string"
      contractIndicator:
        type: "string"
      contactName:
        type: "string"
      phone:
        type: "string"
      webUserId:
        type: "string"
      webUserEmail:
        type: "string"
      odProductCode:
        type: "string"
      productDescription:
        type: "string"
      uom:
        type: "string"
      wholesalerProductCode:
        type: "string"
      packQty:
        type: "number"
        format: "int64"
      qtySold:
        type: "number"
        format: "int64"
      corePlandId:
        type: "number"
        format: "int64"
      netSales:
        type: "number"
        format: "float64"
      contractNetSales:
        type: "number"
        format: "float64"
      listPrice:
        type: "number"
        format: "float64"
      programListPrice:
        type: "number"
        format: "float64"
      parentOrderId:
        type: "string"
      orderSuborderId:
        type: "string"
      orderSourceName:
        type: "string"
      orderSourceCode:
        type: "string"
      productCategoryName:
        type: "string"
      itemDepartmentId:
        type: "number"
        format: "float64"
      itemDepartmentName:
        type: "string"
      itemClassId:
        type: "number"
        format: "float64"
      itemClassName:
        type: "string"
      itemSubclassId:
        type: "number"
        format: "float64"
      itemSubclassName:
        type: "string"
      recycledFlag:
        type: "string"
      primarySupplierId:
        type: "string"
      primarySupplierName:
        type: "string"
      orderSupplierMinorityBusinessCode:
        type: "string"
      orderSupplierMinorityBusinessDesc:
        type: "string"
      orderSupplierMinorityCategoryCode:
        type: "string"
      orderSupplierMinorityCategoryDesc:
        type: "string"
      orderCreateDate:
        type: "string"
        format: "date"
      orderCompleteDate:
        type: "string"
        format: "date"
      inventoryLocation:
        type: "string"
      specialProductId:
        type: "string"
      productId:
        type: "string"
      specialType:
        type: "string"
      specialMod:
        type: "number"
        format: "float64"
      specialLimit:
        type: "number"
        format: "int64"
      totalIssued:
        type: "number"
        format: "int64"
      totalClaimed:
        type: "number"
        format: "int64"
      totalAvailable:
        type: "number"
        format: "int64"
      dateActivated:
        type: "string"
        format: "date"
      dateDeactivated:
        type: "string"
        format: "date"
      specialRestictions:
        type: "string"
    xml:
      name: "ConnectedAccountActivity"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"

#------ EXTERNAL RESOURCES ------
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
